# Generated by Django 5.1.4 on 2025-02-20 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ZajecieFitness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=100)),
                ('instruktor', models.CharField(max_length=100)),
                ('data', models.DateTimeField()),
                ('liczba_miejsc', models.PositiveIntegerField()),
            ],
        ),
    ]
